apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hello-good:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        command: ["python", "archivo_que_no_existe.py"]
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5  
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/"
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"